export const Palette = {
  primary: '#E76006',
  primaryDisabled: '#F88911',
  primaryLight: '#FFF7F2',
  secondary: '#575757',
  dark: '#242424',
  white: '#ffffff',
  background: '#F8F9FA',
  card: '#FFFFFF',
  border: '#ECEEF2',
  borderDark: '#E2E8F0',
  muted: '#F0F1F5',
  textSecondary: '#575757',
  textMuted: '#9AA0A6',
  iconMuted: '#8C93A0',
  success: '#22C55E',
  successDark: '#10B981',
  successBg: '#D1FAE5',
  successBorder: '#6EE7B7',
  successText: '#065F46',
  danger: '#EF4444',
  dangerDark: '#DC2626',
  dangerBg: '#FEE2E2',
  dangerBorder: '#FCA5A5',
  dangerText: '#DC2626',
  warning: '#F59E0B',
} as const;

export const Colors = {
  light: {
    text: Palette.dark,
    textSecondary: Palette.secondary,
    textMuted: Palette.textMuted,
    background: Palette.background,
    backgroundElement: Palette.card,
    backgroundSelected: Palette.muted,
    primary: Palette.primary,
    primaryDisabled: Palette.primaryDisabled,
    primaryLight: Palette.primaryLight,
    secondary: Palette.secondary,
    border: Palette.border,
    borderDark: Palette.borderDark,
    white: Palette.white,
    success: Palette.success,
    successBg: Palette.successBg,
    danger: Palette.danger,
    dangerBg: Palette.dangerBg,
    warning: Palette.warning,
  },
  dark: {
    text: '#ffffff',
    textSecondary: '#B0B4BA',
    textMuted: '#8C93A0',
    background: '#242424',
    backgroundElement: '#2E3135',
    backgroundSelected: '#3D4147',
    primary: Palette.primary,
    primaryDisabled: Palette.primaryDisabled,
    primaryLight: 'rgba(231, 96, 6, 0.15)',
    secondary: Palette.secondary,
    border: '#3D4147',
    borderDark: '#4B5563',
    white: Palette.white,
    success: Palette.success,
    successBg: '#064E3B',
    danger: '#FF6467',
    dangerBg: '#7F1D1D',
    warning: Palette.warning,
  },
} as const;

export type ThemeColor = keyof typeof Colors.light & keyof typeof Colors.dark;
